fixtures:
    symlinks:
        galera: "#{source_dir}"
    repositories:
      apt:
        repo: https://github.com/puppetlabs/puppetlabs-apt.git
        ref: 2.1.0
      stdlib:
        repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
        ref: 4.3.2
    forge_modules:
